#! /usr/bin/env bash

# NOTE this file was generated by gcc-options-parser.sh.mako

args=("$@")
#parsedArgs=()

# default values
iPathList=()
iLangList=()
iLang=none
oPath=a.out

for ((i = 0; i < ${#args[@]}; i++ ))
do
  a=${args[$i]}
  case "$a" in
    -o*)
      [ -n "$oPath" ] && { echo "error: can have only one output"; exit 1; }
      if [ "$a" != "-o" ]; then oPath=${a:2}; else : $((i++)); oPath=${args[$i]}; fi
      echo "o: $oPath"
    ;;
    -x*)
      if [ "$a" != "-x" ]; then iLang=${a:2}; else : $((i++)); iLang=${args[$i]}; fi
      echo "f: $iLang"
    ;;
    -A|-L|-G|-I|-U|-F|-D|-J|-Hd|-Xf|-MQ|-Hf|-MD|-MT|-MF|-MMD|-init|-arch|--dump|-rpath|-iquote|-soname|-assert|-defsym|--assert|-segprot|--output|-isystem|-iprefix|-segaddr|-imacros|-include|--include|-seg1addr|-isysroot|-filelist|--imacros|-undefined|-sectorder|-idirafter|-sectalign|-segcreate|-framework|-imultilib|-rpath-link|-iframework|-sectcreate|-image_base|-dylib_file|-iwithprefix|-client_name|-sub_library|--output-pch|-sub_umbrella|-install_name|-bundle_loader|--define-macro|-pagezero_size|-mtarget-linker|-seg_addr_table|-current_version|--include-prefix|-dependency-file|--undefine-macro|-read_only_relocs|-allowable_client|-multiply_defined|-iwithprefixbefore|-sectobjectsymbols|--include-directory|-segs_read_only_addr|--write-dependencies|-segs_read_write_addr|--include-with-prefix|-dylinker_install_name|-exported_symbols_list|-compatibility_version|-multiply_defined_unused|-unexported_symbols_list|-seg_addr_table_filename|-fintrinsic-modules-path|--include-directory-after|--write-user-dependencies|-weak_reference_mismatches|--include-with-prefix-after|--include-with-prefix-before)
      : $((i++))
      b=${args[$i]}
      echo "2: $a $b"
      #parsedArgs+=("$a" "$b")
    ;;
    -*)
      echo "1: $a"
      #parsedArgs+=("$a")
    ;;
    *)
      echo "i: $a [format: $iLang]"
      iPathList+=("$a")
      # TODO if $iLang == "none", parse language from file extension
      iLangList+=("$iLang")
    ;;
  esac
done
